// GENERATED by scripts/pull-professions.mjs — do not edit by hand.
// The tenant's profession list, committed so the engine can resolve all of them
// with no network and no database. Descriptions are dropped; nothing reads them.
import type { ProfessionRec } from "./professions";

export const PROFESSION_LIST: ProfessionRec[] = [
  {
    "id": 1,
    "name": "Crew",
    "alias": "worker",
    "deleted": false
  },
  {
    "id": 3,
    "name": "Carpenter",
    "alias": null,
    "deleted": false
  },
  {
    "id": 4,
    "name": "Telehandler U&lt; 9M J2 (p/hr)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 5,
    "name": "IPAF 3a/3b",
    "alias": null,
    "deleted": false
  },
  {
    "id": 6,
    "name": "PASMA",
    "alias": null,
    "deleted": false
  },
  {
    "id": 7,
    "name": "Telehandler O&gt; 9M J3 (p/hr)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 9,
    "name": "Driver ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 11,
    "name": "Counterbalance B1 (p/hr)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 12,
    "name": "Followspot ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 13,
    "name": "Crew Audio Tech",
    "alias": null,
    "deleted": true
  },
  {
    "id": 14,
    "name": "Crew Lighting tech ",
    "alias": null,
    "deleted": true
  },
  {
    "id": 16,
    "name": "Crew AV tech",
    "alias": null,
    "deleted": false
  },
  {
    "id": 17,
    "name": "Rough / All Terrain J1 (p/hr)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 22,
    "name": " Counterbalance - (Day Rate) ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 23,
    "name": "Telehandler U&lt; 9M J2 (Day Rate) ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 24,
    "name": "Telehander - O&gt; 9M J3 (Day Rate) ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 25,
    "name": "Rough / All Terrain J1 (Day rate)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 27,
    "name": "Office temp ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 30,
    "name": "Bar Staff",
    "alias": null,
    "deleted": false
  },
  {
    "id": 31,
    "name": "Serving Staff",
    "alias": null,
    "deleted": false
  },
  {
    "id": 32,
    "name": "CSCS Labourer",
    "alias": null,
    "deleted": false
  },
  {
    "id": 35,
    "name": "Host/Hostess",
    "alias": null,
    "deleted": true
  },
  {
    "id": 36,
    "name": "Crew Chief",
    "alias": null,
    "deleted": false
  },
  {
    "id": 38,
    "name": "Recruitment Process",
    "alias": null,
    "deleted": false
  },
  {
    "id": 40,
    "name": "Duty Manager",
    "alias": null,
    "deleted": false
  },
  {
    "id": 41,
    "name": "Office Temp (SCC - Swift)",
    "alias": null,
    "deleted": true
  },
  {
    "id": 42,
    "name": "Office Temp (Crew)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 44,
    "name": "Misc.",
    "alias": null,
    "deleted": false
  },
  {
    "id": 45,
    "name": "Carpool Driver",
    "alias": null,
    "deleted": false
  },
  {
    "id": 46,
    "name": "Minivan Driver",
    "alias": null,
    "deleted": false
  },
  {
    "id": 48,
    "name": "Carpool Driver w/o car",
    "alias": null,
    "deleted": true
  },
  {
    "id": 51,
    "name": "Dummy Tech",
    "alias": null,
    "deleted": true
  },
  {
    "id": 52,
    "name": "Steward",
    "alias": null,
    "deleted": false
  },
  {
    "id": 53,
    "name": "IPAF 1b",
    "alias": null,
    "deleted": false
  },
  {
    "id": 55,
    "name": "Crew Boss",
    "alias": null,
    "deleted": false
  },
  {
    "id": 56,
    "name": "Freelancer",
    "alias": null,
    "deleted": false
  },
  {
    "id": 57,
    "name": "Sunbelt Forks (Day Rate)",
    "alias": null,
    "deleted": false
  },
  {
    "id": 58,
    "name": "Standby Crew",
    "alias": null,
    "deleted": false
  },
  {
    "id": 61,
    "name": "Van Service ",
    "alias": null,
    "deleted": false
  },
  {
    "id": 62,
    "name": "Event Staff",
    "alias": null,
    "deleted": false
  },
  {
    "id": 63,
    "name": "MCR Crew",
    "alias": null,
    "deleted": false
  },
  {
    "id": 64,
    "name": "MCR Crew Chief",
    "alias": null,
    "deleted": false
  },
  {
    "id": 65,
    "name": "Climber ",
    "alias": null,
    "deleted": false
  }
];
