// Writes .env.example: every process.env name read under app/, NAMES ONLY, each with the
// file and line that reads it. Re-run after adding a variable; test/envExample.ts fails
// until you do (SP-52).
//   node scripts/env-names.mjs
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PLATFORM = new Set(["NODE_ENV", "VERCEL", "VERCEL_ENV", "VERCEL_GIT_COMMIT_SHA", "NEXT_RUNTIME"]);

export function envNames(root = "app") {
  const seen = new Map();
  (function walk(dir) {
    for (const e of readdirSync(dir)) {
      const p = join(dir, e);
      if (statSync(p).isDirectory()) walk(p);
      else if (/\.(ts|tsx|mjs|js)$/.test(e)) {
        readFileSync(p, "utf8").split("\n").forEach((line, i) => {
          for (const m of line.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)/g)) {
            if (!seen.has(m[1])) seen.set(m[1], `${p.replace(/\\/g, "/")}:${i + 1}`);
          }
        });
      }
    }
  })(root);
  return seen;
}

if (process.argv[1] && process.argv[1].endsWith("env-names.mjs")) {
  const names = [...envNames().entries()].sort(([a], [b]) => a.localeCompare(b));
  const out = [
    "# Every environment variable the app reads, NAMES ONLY. Never put a value in this file.",
    "# Generated by scripts/env-names.mjs; test/envExample.ts fails when code reads a name not listed.",
    "",
    ...names.flatMap(([n, where]) => [`# ${where}${PLATFORM.has(n) ? " (set by the platform, not by us)" : ""}`, `${n}=`, ""]),
  ];
  writeFileSync(".env.example", out.join("\n"));
  console.log(`.env.example: ${names.length} names`);
}
